kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-kubeflow
  namespace: kubeflow
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
